#!/usr/local/bin/julia
println("1. Create two matrices of the same layout and test if addition and subtraction of the matrix works as expected: C = A + B ")
matrix1 = rand(1:10, (2,4))
matrix2 = rand(1:10, (2,4))
println("Matrix 1: ")
display(matrix1)
println()
println("Matrix 2: ")
display(matrix2)
println()

println("##### MATRIX ADDITION #####")
println("matrix1 + matrix2 = ?")
display(matrix1 + matrix2)
println()

println("2. Now compare matrix multiplication either this way A * B and this way A .* B. Whats the difference?! ")
println("##### MATRIX MULTIPLICATION #####")
println("matrix1 * T(matrix2)")
display(matrix1 * transpose(matrix2))
println()
println("matrix1 .* matrix2")
display(matrix1 .* matrix2)
println()

println("3. What about matrix division with '/' or 'backslash'?! ")
println("###### MATRIX DIVISTION #####")
println("matrix1 / matrix2 = ?")
display(matrix1 / matrix2)
println()
println("backslash division of matrix1 and matrix2 = ?")
display(matrix1 \ matrix2)
println()

println("4. Create a 3x3 integer matrix A with useful numbers. Now try A+1, A-1, A*2, A/2. ")
matrix3 = rand(1:10, (3,3))
display(matrix3)
println()

println("A .+ 1 = ?")
display(matrix3 .+ 1)
println()

println("A .- 1 = ?")
display(matrix3 .- 1)
println()

println("A * 2 = ?")
display(matrix3 * 2)
println()

println("A / 2 = ?")
display(matrix3 / 2)
println()

println("5. Now multiply a 3x4 matrix with a suitable (4)vector. ")
matrix4 = rand(1:10, (3,4))
vector1 = rand(1:10, 4)
display(matrix4)
println()
display(vector1)
println()
println("matrix4 * vector1 = ?")
display(matrix4 * vector1)
println()
